#!/bin/bash
defaultMiner=https://github.com/ethereum-mining/ethminer/releases/download/v0.14.0rc4/ethminer-0.14.0rc4-Linux.tar.gz

git clone https://github.com/xcalibur839/ethscripts.git ~/mining
chmod +x ~/mining/setup/setup
~/mining/setup/setup
echo
echo
echo "Do you have AMD cards, NVIDIA cards, Both, or do you want to Skip installing drivers?"
select anbs in "AMD" "NVIDIA" "Both" "Skip"; do
    case $anbs in
        AMD ) ~/mining/setup/install-AMD-drivers; break;;
        NVIDIA ) ~/mining/setup/install-NVIDIA-drivers; break;;
        Both ) ~/mining/setup/install-AMD-drivers && ~/mining/setup/install-NVIDIA-drivers; break;;
        Skip ) break;;
    esac
done
echo
echo
echo "Would you like to detect temp sensors on this machine? (optional)"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) sudo ~/mining/setup/detect-temp-sensors; break;;
        No ) break;;
    esac
done
echo
echo
echo "Would you like to download the default miner? (optional)"
echo "You will need to install ethminer before you can mine."
echo "If you don't download the default, use the getNewMiner script with the .tar.gz URL from github."
select install in "Download" "Skip"; do
    case $install in
        Download ) ~/getNewMiner $defaultMiner; break;;
        Skip ) break;;
    esac
done
echo
echo
echo "Please configure your miner settings"
read -p "Press Enter to continue"
nano ~/mining/config.txt
echo
echo
echo "****Your system has been set up and needs to reboot****"
echo
echo "This script will now automatically reboot the system."
echo
echo "When the system reboots, run the start script in your home folder (~/start)"
read -p "Press Enter to reboot or Ctrl + c to exit"
sudo reboot
